In [2]:
import pandas as pd

df = pd.read_pickle("/scratch/data/ROAMM/derivatives/synced/sub-10014/sub-10014_task-ReMind_run-01_mldata.pkl")

df.head()

,Fp1,AF7,AF3,F1,F3,F5,F7,FT7,FC5,FC3,...,LPupil,RX,RY,RPupil,blink_interp_LX,blink_interp_LY,blink_interp_LPupil,blink_interp_RX,blink_interp_RY,blink_interp_RPupil
0,0.000010,-0.000009,-1.296942e-06,-1.143055e-07,-0.000009,-0.000008,-0.000014,-0.000009,-0.000009,-2.477431e-06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.000013,-0.000005,-1.211723e-06,-1.628259e-06,-0.000010,-0.000008,-0.000013,-0.000009,-0.000009,-2.405989e-06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.000015,-0.000003,-6.835898e-07,-2.152282e-06,-0.000009,-0.000006,-0.000010,-0.000007,-0.000007,-1.101047e-06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.000013,-0.000005,-9.610865e-07,-2.243665e-06,-0.000008,-0.000005,-0.000007,-0.000005,-0.000005,1.571541e-07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.000009,-0.000010,-2.379462e-06,-2.803911e-06,-0.000008,-0.000006,-0.000009,-0.000006,-0.000005,1.974937e-07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
df.columns.tolist()

['Fp1',
 'AF7',
 'AF3',
 'F1',
 'F3',
 'F5',
 'F7',
 'FT7',
 'FC5',
 'FC3',
 'FC1',
 'C1',
 'C3',
 'C5',
 'T7',
 'TP7',
 'CP5',
 'CP3',
 'CP1',
 'P1',
 'P3',
 'P5',
 'P7',
 'P9',
 'PO7',
 'PO3',
 'O1',
 'Iz',
 'Oz',
 'POz',
 'Pz',
 'CPz',
 'Fpz',
 'Fp2',
 'AF8',
 'AF4',
 'Afz',
 'Fz',
 'F2',
 'F4',
 'F6',
 'F8',
 'FT8',
 'FC6',
 'FC4',
 'FC2',
 'FCz',
 'Cz',
 'C2',
 'C4',
 'C6',
 'T8',
 'TP8',
 'CP6',
 'CP4',
 'CP2',
 'P2',
 'P4',
 'P6',
 'P8',
 'P10',
 'PO8',
 'PO4',
 'O2',
 'time',
 'sfreq',
 'first_pass_reading',
 'page_num',
 'page_start',
 'page_end',
 'page_dur',
 'is_mw',
 'mw_onset',
 'mw_offset',
 'mw_dur',
 'run_num',
 'story_name',
 'is_fix',
 'fix_L_eye',
 'fix_L_tStart',
 'fix_L_tEnd',
 'fix_L_duration',
 'fix_L_xAvg',
 'fix_L_yAvg',
 'fix_L_pupilAvg',
 'fix_L_fixed_word',
 'fix_L_fixed_word_key',
 'fix_R_eye',
 'fix_R_tStart',
 'fix_R_tEnd',
 'fix_R_duration',
 'fix_R_xAvg',
 'fix_R_yAvg',
 'fix_R_pupilAvg',
 'fix_R_fixed_word',
 'fix_R_fixed_word_key',
 'is_blink',
 'blink_L_eye',
 'blink_L_tStart',
 'blink_L_tEnd',
 'blink_L_duration',
 'blink_R_eye',
 'blink_R_tStart',
 'blink_R_tEnd',
 'blink_R_duration',
 'is_sacc',
 'sacc_L_eye',
 'sacc_L_tStart',
 'sacc_L_tEnd',
 'sacc_L_duration',
 'sacc_L_xStart',
 'sacc_L_yStart',
 'sacc_L_xEnd',
 'sacc_L_yEnd',
 'sacc_L_ampDeg',
 'sacc_L_vPeak',
 'sacc_R_eye',
 'sacc_R_tStart',
 'sacc_R_tEnd',
 'sacc_R_duration',
 'sacc_R_xStart',
 'sacc_R_yStart',
 'sacc_R_xEnd',
 'sacc_R_yEnd',
 'sacc_R_ampDeg',
 'sacc_R_vPeak',
 'tSample',
 'LX',
 'LY',
 'LPupil',
 'RX',
 'RY',
 'RPupil',
 'blink_interp_LX',
 'blink_interp_LY',
 'blink_interp_LPupil',
 'blink_interp_RX',
 'blink_interp_RY',
 'blink_interp_RPupil']

In [42]:
df["story_name"]

0         serena_williams
1         serena_williams
2         serena_williams
3         serena_williams
4         serena_williams
               ...
121083    serena_williams
121084    serena_williams
121085    serena_williams
121086    serena_williams
121087    serena_williams
Name: story_name, Length: 121088, dtype: str

In [5]:
df[["first_pass_reading", "is_mw", "is_fix"]].value_counts(dropna=False)

first_pass_reading  is_mw  is_fix
NaN                 NaN    True      95802
True                NaN    True      32397
NaN                 NaN    False     18850
True                True   True      12651
                    NaN    False      5830
                    True   False      3174
Name: count, dtype: int64

In [6]:
df["first_pass_reading"].value_counts(dropna=False)

first_pass_reading
NaN     114652
True     54052
Name: count, dtype: int64

In [7]:
df["is_mw"].value_counts(dropna=False)

is_mw
NaN     152879
True     15825
Name: count, dtype: int64

In [8]:
df["is_fix"].value_counts(dropna=False)

is_fix
True     140850
False     27854
Name: count, dtype: int64

In [15]:
all_fix = df["fix_L_tStart"].dropna().unique()

first_fix = df.loc[df["first_pass_reading"].eq(True), "fix_L_tStart"].dropna().unique()

print("all fixations:", len(all_fix))
print("first-pass fixations:", len(first_fix))
print("excluded:", len(all_fix) - len(first_fix))
print("excluded %:", (len(all_fix) - len(first_fix)) / len(all_fix) * 100)

all fixations: 2558
first-pass fixations: 824
excluded: 1734
excluded %: 67.78733385457389

In [ ]:
# Dropped fixations are the non-text fixations
dropped = df.loc[
    df["first_pass_reading"].isna()
    & df["fix_L_tStart"].notna()
].drop_duplicates("fix_L_tStart")

print("Dropped fixations:", len(dropped))
print("with fixed word:", dropped["fix_L_fixed_word"].notna().sum())
print("With word key:", dropped["fix_L_fixed_word_key"].notna().sum())

Dropped fixations: 1754
with fixed word: 0
With word key: 0

In [27]:
all_fix = set(df["fix_L_tStart"].dropna().unique())

first_fix = set(
    df.loc[
        df["first_pass_reading"].eq(True),
        "fix_L_tStart"
    ].dropna().unique()
)

nonfirst_fix = set(
    df.loc[
        df["first_pass_reading"].isna(),
        "fix_L_tStart"
    ].dropna().unique()
)

print("all:", len(all_fix))
print("first-pass:", len(first_fix))
print("non-first-pass:", len(nonfirst_fix))
print("overlap:", len(first_fix & nonfirst_fix))

all: 2558
first-pass: 824
non-first-pass: 1754
overlap: 20

In [28]:
# Valid trials
valid = (
    df.loc[
        df["first_pass_reading"].eq(True)
        & df["fix_L_tStart"].notna()
        & df["fix_L_fixed_word"].notna()
        & df["fix_L_fixed_word_key"].notna()
    ].drop_duplicates("fix_L_tStart")
)

print("Valid fixations:", len(valid))

Valid fixations: 790

In [30]:
valid[
    [
        "time",
        "page_num",
        "story_name",
        "fix_L_fixed_word",
        "fix_L_fixed_word_key",
        "fix_L_tStart",
    ]
].head(50)

,time,page_num,story_name,fix_L_fixed_word,fix_L_fixed_word_key,fix_L_tStart
3316,12.953125,0.0,pluto,volume.,202ed870-fb4d-4f17-90d9-b9e119a96ae3,12.950262
3393,13.253906,0.0,pluto,volume.,202ed870-fb4d-4f17-90d9-b9e119a96ae3,13.252263
3438,13.429688,0.0,pluto,(minor-planet,43e85048-6af0-4195-8627-796a1189f9e8,13.426262
3479,13.589844,0.0,pluto,Pluto,b73180a5-011d-42d5-8c12-2a4acb4344b4,13.587263
3580,13.984375,0.0,pluto,(minor-planet,43e85048-6af0-4195-8627-796a1189f9e8,13.983263
3634,14.195312,0.0,pluto,(minor-planet,43e85048-6af0-4195-8627-796a1189f9e8,14.194263
3699,14.449219,0.0,pluto,designation:,f5513591-945c-4090-85cc-13e439346527,14.446262
3749,14.644531,0.0,pluto,134340,d3f7e9f7-0d0d-4e4e-8298-ee17bb5e29e2,14.643262
3805,14.863281,0.0,pluto,Pluto),c60b20f4-8d7a-4c39-bb63-7bc5394cd142,14.860262
3865,15.097656,0.0,pluto,dwarf,c7cd30e1-24df-43c8-ad39-9d9c08cb856d,15.095262
3937,15.378906,0.0,pluto,planet,cbe7cad4-36ea-4dc5-8157-e71bbe2002fe,15.377263
3991,15.589844,0.0,pluto,the,ebcb6307-11bd-49e8-9078-1c6fcdb5fa6e,15.589262
4048,15.812500,0.0,pluto,in,fe65efa4-b374-4e1a-ba06-08021a3880bb,15.810262
4096,16.000000,0.0,pluto,Kuiper,7fb77180-2c52-482b-a563-f940b8b0e43b,15.998262
4149,16.207031,0.0,pluto,Kuiper,7fb77180-2c52-482b-a563-f940b8b0e43b,16.206262
4241,16.566406,0.0,pluto,"belt,",588e85ba-de6b-4700-96a0-3c47b1b6c995,16.563263
4276,16.703125,0.0,pluto,Pluto,b73180a5-011d-42d5-8c12-2a4acb4344b4,16.701262
4368,17.062500,0.0,pluto,ring,439a3e2b-e999-4bb1-91c5-578f41ef0ec5,17.062262
4439,17.339844,0.0,pluto,bodies,fdd97410-2e1e-4b62-80e0-2ed6c383ba6c,17.338263
4480,17.500000,0.0,pluto,ring,439a3e2b-e999-4bb1-91c5-578f41ef0ec5,17.497263
4545,17.753906,0.0,pluto,bodies,fdd97410-2e1e-4b62-80e0-2ed6c383ba6c,17.751263
4606,17.992188,0.0,pluto,beyond,6d8297b2-9e22-4c31-9d25-521966e635e9,17.989262
4677,18.269531,0.0,pluto,Neptune.,a0c74dd6-def7-4182-842d-a36cb0c02086,18.267262
4737,18.503906,0.0,pluto,was,35334716-da86-442e-bbe8-1bc0fab9954f,18.502263
4794,18.726562,0.0,pluto,first,1260f65e-23fc-448b-8b19-d2788912c8d2,18.726262
4858,18.976562,0.0,pluto,Kuiper,3cb1233b-c5b1-4dad-8a24-80af1dcfdeee,18.976262
4918,19.210938,0.0,pluto,belt,20924a00-9628-48e8-9964-4f30cbc28fa0,19.210262
4967,19.402344,0.0,pluto,Kuiper,3cb1233b-c5b1-4dad-8a24-80af1dcfdeee,19.399262
5029,19.644531,0.0,pluto,Kuiper,3cb1233b-c5b1-4dad-8a24-80af1dcfdeee,19.644262
5070,19.804688,0.0,pluto,was,35334716-da86-442e-bbe8-1bc0fab9954f,19.804263
5134,20.054688,0.0,pluto,the,278c23a5-b5f5-4a51-aacb-7bc2d91cfae8,20.054263
5208,20.343750,0.0,pluto,planet,cbe7cad4-36ea-4dc5-8157-e71bbe2002fe,20.341262
5252,20.515625,0.0,pluto,in,fe65efa4-b374-4e1a-ba06-08021a3880bb,20.512262
5330,20.820312,0.0,pluto,in,fe65efa4-b374-4e1a-ba06-08021a3880bb,20.817262
5383,21.027344,0.0,pluto,the,ebcb6307-11bd-49e8-9078-1c6fcdb5fa6e,21.026263
5427,21.199219,0.0,pluto,Kuiper,7fb77180-2c52-482b-a563-f940b8b0e43b,21.196262
5480,21.406250,0.0,pluto,discovered.,4dd06875-1b72-4845-a55e-831d2c74b332,21.403262
5573,21.769531,0.0,pluto,It,bbc0c0e3-4707-4421-96ba-bb0a8323865b,21.769262
5638,22.023438,0.0,pluto,largest,80b697c7-57b8-4d18-8a90-33e7012b7acb,22.023262
5758,22.492188,0.0,pluto,It,bbc0c0e3-4707-4421-96ba-bb0a8323865b,22.491263
5819,22.730469,0.0,pluto,largest,80b697c7-57b8-4d18-8a90-33e7012b7acb,22.729262
5872,22.937500,0.0,pluto,second-most,942ee6d7-b297-4b52-9a6a-844b65acd254,22.935263
5943,23.214844,0.0,pluto,massive,84f910ea-9c50-43bc-b229-9774a2bd5bd2,23.212263
5990,23.398438,0.0,pluto,massive,84f910ea-9c50-43bc-b229-9774a2bd5bd2,23.398262
6044,23.609375,0.0,pluto,dwarf,16640b40-b4c1-4518-b263-9ecb88c0d353,23.609262
6103,23.839844,0.0,pluto,dwarf,16640b40-b4c1-4518-b263-9ecb88c0d353,23.839262
6167,24.089844,0.0,pluto,the,278c23a5-b5f5-4a51-aacb-7bc2d91cfae8,24.088263
15444,60.328125,1.0,pluto,either,2e51ea2f-218a-479d-9594-0260e09e472c,60.325262
15535,60.683594,1.0,pluto,within,e3423dec-f532-47b4-8365-0d00d59db5ab,60.680263
15598,60.929688,1.0,pluto,within,e3423dec-f532-47b4-8365-0d00d59db5ab,60.927262

In [31]:
print("First-pass fixations:", len(first_fix))
print("Valid lexical trials:", len(valid))
print("Dropped within first-pass:", len(first_fix) - len(valid))

First-pass fixations: 824
Valid lexical trials: 790
Dropped within first-pass: 34

In [35]:
first_pass = (
    df.loc[
        df["first_pass_reading"].eq(True)
        & df["fix_R_tStart"].notna()
    ]
    .drop_duplicates("fix_R_tStart")
)

invalid = first_pass[
    first_pass["fix_R_fixed_word"].isna()
    | first_pass["fix_R_fixed_word_key"].isna()
]

print("Invalid first-pass fixations:", len(invalid))

invalid[
    [
        "time",
        "page_num",
        "fix_R_tStart",
        "fix_R_xAvg",
        "fix_R_yAvg",
        "fix_R_fixed_word",
        "fix_R_fixed_word_key",
    ]
].head(50)

Invalid first-pass fixations: 38

,time,page_num,fix_R_tStart,fix_R_xAvg,fix_R_yAvg,fix_R_fixed_word,fix_R_fixed_word_key
3215,12.558594,0.0,12.220262,798.0,508.3,NaN,NaN
6229,24.332031,0.0,24.331262,1146.9,45.7,NaN,NaN
15398,60.148438,1.0,59.473263,1449.3,501.0,NaN,NaN
26855,104.902344,1.0,104.901263,592.5,838.0,NaN,NaN
31456,122.875000,2.0,122.839262,309.8,0.6,NaN,NaN
34022,132.898438,2.0,132.897262,1437.8,94.7,NaN,NaN
44191,172.621094,3.0,172.267263,672.3,771.9,NaN,NaN
53303,208.214844,3.0,208.214262,1054.0,708.7,NaN,NaN
60080,234.687500,4.0,234.542262,474.6,35.3,NaN,NaN
66205,258.613281,4.0,258.612262,1458.5,441.2,NaN,NaN
70691,276.136719,5.0,275.990263,440.5,475.2,NaN,NaN
73795,288.261719,5.0,288.260263,290.5,12.3,NaN,NaN
83615,326.621094,6.0,326.423263,1017.0,554.8,NaN,NaN
84718,330.929688,6.0,330.926263,905.7,-73.2,NaN,NaN
84786,331.195312,6.0,331.194263,865.7,-69.9,NaN,NaN
96714,377.789062,7.0,377.078263,924.5,832.8,NaN,NaN
97519,380.933594,7.0,380.930262,730.8,1488.5,NaN,NaN
98414,384.429688,7.0,384.426263,1383.1,-69.6,NaN,NaN
98518,384.835938,7.0,384.833262,1446.1,-86.2,NaN,NaN
98570,385.039062,7.0,385.035262,1561.0,-96.8,NaN,NaN
104066,406.507812,7.0,406.506262,906.1,313.7,NaN,NaN
113570,443.632812,8.0,443.015262,1097.3,873.1,NaN,NaN
114328,446.593750,8.0,446.591262,481.3,-71.7,NaN,NaN
114774,448.335938,8.0,448.332262,1286.1,-79.2,NaN,NaN
114823,448.527344,8.0,448.524262,1400.2,-90.0,NaN,NaN
114885,448.769531,8.0,448.768263,1534.7,-116.0,NaN,NaN
117276,458.109375,8.0,458.109262,366.9,-10.1,NaN,NaN
124056,484.593750,9.0,483.679262,1063.3,505.9,NaN,NaN
124746,487.289062,9.0,487.285262,387.0,-72.2,NaN,NaN
124848,487.687500,9.0,487.687262,652.5,-73.4,NaN,NaN
124915,487.949219,9.0,487.946262,843.6,-79.8,NaN,NaN
125041,488.441406,9.0,488.440263,1145.7,-86.5,NaN,NaN
125100,488.671875,9.0,488.668262,1365.0,-105.6,NaN,NaN
125150,488.867188,9.0,488.865263,1451.2,-120.8,NaN,NaN
125200,489.062500,9.0,489.062262,1575.5,-132.6,NaN,NaN
125251,489.261719,9.0,489.261263,1449.7,-124.3,NaN,NaN
125358,489.679688,9.0,489.679262,1566.8,-129.2,NaN,NaN
129769,506.910156,9.0,506.909262,1073.7,125.5,NaN,NaN

In [36]:
first_pass = (
    df.loc[
        df["first_pass_reading"].eq(True)
        & df["fix_L_tStart"].notna()
    ]
    .drop_duplicates("fix_L_tStart")
)

left_missing = first_pass[
    first_pass["fix_L_fixed_word_key"].isna()
]

print("Left-eye missing word key:", len(left_missing))

print(
    "But right eye has word key:",
    left_missing["fix_R_fixed_word_key"].notna().sum()
)

Left-eye missing word key: 34
But right eye has word key: 5

In [37]:
left_missing[
    [
        "fix_L_tStart",
        "fix_L_fixed_word",
        "fix_L_fixed_word_key",
        "fix_R_tStart",
        "fix_R_fixed_word",
        "fix_R_fixed_word_key",
    ]
].head(30)

,fix_L_tStart,fix_L_fixed_word,fix_L_fixed_word_key,fix_R_tStart,fix_R_fixed_word,fix_R_fixed_word_key
3215,12.222263,NaN,NaN,12.220262,NaN,NaN
6229,24.330262,NaN,NaN,24.331262,NaN,NaN
15398,59.482263,NaN,NaN,59.473263,NaN,NaN
26854,104.898262,NaN,NaN,NaN,NaN,NaN
31456,122.839262,NaN,NaN,122.839262,NaN,NaN
31732,123.950262,NaN,NaN,123.949263,besides,8d2bacc2-fa1a-4378-ba68-27fc0aa02a94
32155,125.602263,NaN,NaN,125.602263,Lowell,7e53859d-2953-43e8-a609-708e752ceb50
32393,126.531262,NaN,NaN,126.531262,--,e651fa52-8a8d-470e-80c3-6e867b688a64
32455,126.777262,NaN,NaN,126.775263,wealthy,b924630a-17c3-4880-af50-c597487753f7
32543,127.117263,NaN,NaN,127.113262,wealthy,b924630a-17c3-4880-af50-c597487753f7
34021,132.894262,NaN,NaN,NaN,NaN,NaN
44191,172.267263,NaN,NaN,172.267263,NaN,NaN
53303,208.214262,NaN,NaN,208.214262,NaN,NaN
60080,234.539263,NaN,NaN,234.542262,NaN,NaN
66205,258.612262,NaN,NaN,258.612262,NaN,NaN
70691,275.990263,NaN,NaN,275.990263,NaN,NaN
73795,288.259263,NaN,NaN,288.260263,NaN,NaN
83615,326.423263,NaN,NaN,326.423263,NaN,NaN
84785,331.191263,NaN,NaN,NaN,NaN,NaN
96714,377.077263,NaN,NaN,377.078263,NaN,NaN
97518,380.928262,NaN,NaN,NaN,NaN,NaN
104066,406.504262,NaN,NaN,406.506262,NaN,NaN
113570,443.008263,NaN,NaN,443.015262,NaN,NaN
114325,446.580263,NaN,NaN,NaN,NaN,NaN
114885,448.768263,NaN,NaN,448.768263,NaN,NaN
117276,458.107263,NaN,NaN,458.109262,NaN,NaN
124056,483.678262,NaN,NaN,483.679262,NaN,NaN
124745,487.284262,NaN,NaN,NaN,NaN,NaN
124785,487.441263,NaN,NaN,NaN,NaN,NaN
125150,488.865263,NaN,NaN,488.865263,NaN,NaN

# To check whether to use right eye or left eye

In [39]:
from pathlib import Path
import pandas as pd

files = sorted(
    Path("/scratch/data/ROAMM/derivatives/synced")
    .glob("sub-*/*_mldata.pkl")
)

rows = []

for file in files:
    df = pd.read_pickle(file)

    subject = file.parent.name
    run = int(df["run_num"].dropna().iloc[0])

    for eye in ["L", "R"]:
        tstart = f"fix_{eye}_tStart"
        word_key = f"fix_{eye}_fixed_word_key"

        if tstart not in df.columns or word_key not in df.columns:
            print(f"Skip {subject} run {run}, eye {eye}: columns missing")
            continue

        first_pass = (
            df.loc[
                df["first_pass_reading"].eq(True)
                & df[tstart].notna(),
                [tstart, word_key]
            ]
            .drop_duplicates(tstart)
        )

        rows.append({
            "subject": subject,
            "run": run,
            "eye": eye,
            "first_pass_fixations": len(first_pass),
            "valid_lexical_fixations": first_pass[word_key].notna().sum(),
            "missing_word": first_pass[word_key].isna().sum(),
        })

summary = pd.DataFrame(rows)

Skip sub-10141 run 3, eye L: columns missing

In [40]:
summary.groupby("eye")[
    ["first_pass_fixations",
     "valid_lexical_fixations",
     "missing_word"]
].sum()

     first_pass_fixations  valid_lexical_fixations  missing_word
eye
L                  409313                   404557          4756
R                  411182                   406751          4431